### ISSUE TITLE
tpx_uv tpx_h的请求

### ISSUE THREAD

**Issue by zhxn30663** [autodotua/my_coawst_tools#1]
你好，我想问一下tpx_uv和tpx_h这两个mat是失效了吗？readme里的sourcerepo网站用IE也还是一直在要求用户名和密码，用svn也还是绕不开，方便的话能传一下吗？再次感谢！
zhxn30663@163.com

**Comment by autodotua** [comment]
> 你好，我想问一下tpx_uv和tpx_h这两个mat是失效了吗？readme里的sourcerepo网站用IE也还是一直在要求用户名和密码，用svn也还是绕不开，方便的话能传一下吗？再次感谢！ [zhxn30663@163.com](mailto:zhxn30663@163.com)

你好，已发送下载地址，请查收。如果没收到可以再回复。

**Comment by zhxn30663** [comment]
非常感谢！已经收到了！
